# Generated by Django 3.2.9 on 2021-11-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MediaMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(upload_to='posters')),
                ('casts', models.ManyToManyField(blank=True, null=True, to='multimedia.Actor')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='multimedia.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mediameta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multimedia.mediameta')),
            ],
            bases=('multimedia.mediameta',),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('mediameta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multimedia.mediameta')),
                ('num_of_eposides', models.IntegerField()),
            ],
            bases=('multimedia.mediameta',),
        ),
    ]
