# Generated by Django 3.2.9 on 2021-11-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0006_auto_20211106_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNum', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='idnum',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedb.actorid'),
        ),
    ]
