# Generated by Django 3.2.9 on 2021-11-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0007_auto_20211106_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie/posters'),
        ),
    ]
