on:
        push:
                branches: 
                        - main
                paths:
                        - shell-script/**
jobs:
 test:
  name: Run test
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@master
  - uses: mr-smithers-excellent/docker-build-push@v5
    name: Build & push Docker image
    with:
      image: compilereg/pythoncgi
      tags: v1, latest
      registry: docker.io
      dockerfile: Dockerfile
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
